// Code generated by go-swagger; DO NOT EDIT.

package families

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFamilyParams creates a new GetFamilyParams object
// with the default values initialized.
func NewGetFamilyParams() *GetFamilyParams {
	var ()
	return &GetFamilyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFamilyParamsWithTimeout creates a new GetFamilyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFamilyParamsWithTimeout(timeout time.Duration) *GetFamilyParams {
	var ()
	return &GetFamilyParams{

		timeout: timeout,
	}
}

// NewGetFamilyParamsWithContext creates a new GetFamilyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFamilyParamsWithContext(ctx context.Context) *GetFamilyParams {
	var ()
	return &GetFamilyParams{

		Context: ctx,
	}
}

// NewGetFamilyParamsWithHTTPClient creates a new GetFamilyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFamilyParamsWithHTTPClient(client *http.Client) *GetFamilyParams {
	var ()
	return &GetFamilyParams{
		HTTPClient: client,
	}
}

/*GetFamilyParams contains all the parameters to send to the API endpoint
for the get family operation typically these are written to a http.Request
*/
type GetFamilyParams struct {

	/*FamilyID
	  The id of the Family to look up.

	*/
	FamilyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get family params
func (o *GetFamilyParams) WithTimeout(timeout time.Duration) *GetFamilyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get family params
func (o *GetFamilyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get family params
func (o *GetFamilyParams) WithContext(ctx context.Context) *GetFamilyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get family params
func (o *GetFamilyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get family params
func (o *GetFamilyParams) WithHTTPClient(client *http.Client) *GetFamilyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get family params
func (o *GetFamilyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFamilyID adds the familyID to the get family params
func (o *GetFamilyParams) WithFamilyID(familyID string) *GetFamilyParams {
	o.SetFamilyID(familyID)
	return o
}

// SetFamilyID adds the familyId to the get family params
func (o *GetFamilyParams) SetFamilyID(familyID string) {
	o.FamilyID = familyID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFamilyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param family_id
	if err := r.SetPathParam("family_id", o.FamilyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
