// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetResourceTypesParams creates a new GetResourceTypesParams object
// with the default values initialized.
func NewGetResourceTypesParams() *GetResourceTypesParams {
	var ()
	return &GetResourceTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourceTypesParamsWithTimeout creates a new GetResourceTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetResourceTypesParamsWithTimeout(timeout time.Duration) *GetResourceTypesParams {
	var ()
	return &GetResourceTypesParams{

		timeout: timeout,
	}
}

// NewGetResourceTypesParamsWithContext creates a new GetResourceTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetResourceTypesParamsWithContext(ctx context.Context) *GetResourceTypesParams {
	var ()
	return &GetResourceTypesParams{

		Context: ctx,
	}
}

// NewGetResourceTypesParamsWithHTTPClient creates a new GetResourceTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetResourceTypesParamsWithHTTPClient(client *http.Client) *GetResourceTypesParams {
	var ()
	return &GetResourceTypesParams{
		HTTPClient: client,
	}
}

/*GetResourceTypesParams contains all the parameters to send to the API endpoint
for the get resource types operation typically these are written to a http.Request
*/
type GetResourceTypesParams struct {

	/*BetaResources
	  Indicates whether resource types in beta will be returned.

	*/
	BetaResources *bool
	/*Provider
	  Name of the cloud provider.

	*/
	Provider string
	/*Region
	  The AWS region for which to return resource types.  Required if provider is aws or aws_govcloud.

	*/
	Region *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get resource types params
func (o *GetResourceTypesParams) WithTimeout(timeout time.Duration) *GetResourceTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource types params
func (o *GetResourceTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource types params
func (o *GetResourceTypesParams) WithContext(ctx context.Context) *GetResourceTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource types params
func (o *GetResourceTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource types params
func (o *GetResourceTypesParams) WithHTTPClient(client *http.Client) *GetResourceTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource types params
func (o *GetResourceTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBetaResources adds the betaResources to the get resource types params
func (o *GetResourceTypesParams) WithBetaResources(betaResources *bool) *GetResourceTypesParams {
	o.SetBetaResources(betaResources)
	return o
}

// SetBetaResources adds the betaResources to the get resource types params
func (o *GetResourceTypesParams) SetBetaResources(betaResources *bool) {
	o.BetaResources = betaResources
}

// WithProvider adds the provider to the get resource types params
func (o *GetResourceTypesParams) WithProvider(provider string) *GetResourceTypesParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get resource types params
func (o *GetResourceTypesParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithRegion adds the region to the get resource types params
func (o *GetResourceTypesParams) WithRegion(region *string) *GetResourceTypesParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get resource types params
func (o *GetResourceTypesParams) SetRegion(region *string) {
	o.Region = region
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourceTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BetaResources != nil {

		// query param beta_resources
		var qrBetaResources bool
		if o.BetaResources != nil {
			qrBetaResources = *o.BetaResources
		}
		qBetaResources := swag.FormatBool(qrBetaResources)
		if qBetaResources != "" {
			if err := r.SetQueryParam("beta_resources", qBetaResources); err != nil {
				return err
			}
		}

	}

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
