// Code generated by go-swagger; DO NOT EDIT.

package custom_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCustomRuleParams creates a new DeleteCustomRuleParams object
// with the default values initialized.
func NewDeleteCustomRuleParams() *DeleteCustomRuleParams {
	var ()
	return &DeleteCustomRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomRuleParamsWithTimeout creates a new DeleteCustomRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCustomRuleParamsWithTimeout(timeout time.Duration) *DeleteCustomRuleParams {
	var ()
	return &DeleteCustomRuleParams{

		timeout: timeout,
	}
}

// NewDeleteCustomRuleParamsWithContext creates a new DeleteCustomRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCustomRuleParamsWithContext(ctx context.Context) *DeleteCustomRuleParams {
	var ()
	return &DeleteCustomRuleParams{

		Context: ctx,
	}
}

// NewDeleteCustomRuleParamsWithHTTPClient creates a new DeleteCustomRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCustomRuleParamsWithHTTPClient(client *http.Client) *DeleteCustomRuleParams {
	var ()
	return &DeleteCustomRuleParams{
		HTTPClient: client,
	}
}

/*DeleteCustomRuleParams contains all the parameters to send to the API endpoint
for the delete custom rule operation typically these are written to a http.Request
*/
type DeleteCustomRuleParams struct {

	/*RuleID
	  The id of the rule to delete.

	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete custom rule params
func (o *DeleteCustomRuleParams) WithTimeout(timeout time.Duration) *DeleteCustomRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete custom rule params
func (o *DeleteCustomRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete custom rule params
func (o *DeleteCustomRuleParams) WithContext(ctx context.Context) *DeleteCustomRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete custom rule params
func (o *DeleteCustomRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete custom rule params
func (o *DeleteCustomRuleParams) WithHTTPClient(client *http.Client) *DeleteCustomRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete custom rule params
func (o *DeleteCustomRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the delete custom rule params
func (o *DeleteCustomRuleParams) WithRuleID(ruleID string) *DeleteCustomRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the delete custom rule params
func (o *DeleteCustomRuleParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rule_id
	if err := r.SetPathParam("rule_id", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
