// Code generated by go-swagger; DO NOT EDIT.

package custom_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fugue/regula/v2/pkg/swagger/models"
)

// NewUpdateCustomRuleParams creates a new UpdateCustomRuleParams object
// with the default values initialized.
func NewUpdateCustomRuleParams() *UpdateCustomRuleParams {
	var ()
	return &UpdateCustomRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCustomRuleParamsWithTimeout creates a new UpdateCustomRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCustomRuleParamsWithTimeout(timeout time.Duration) *UpdateCustomRuleParams {
	var ()
	return &UpdateCustomRuleParams{

		timeout: timeout,
	}
}

// NewUpdateCustomRuleParamsWithContext creates a new UpdateCustomRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCustomRuleParamsWithContext(ctx context.Context) *UpdateCustomRuleParams {
	var ()
	return &UpdateCustomRuleParams{

		Context: ctx,
	}
}

// NewUpdateCustomRuleParamsWithHTTPClient creates a new UpdateCustomRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCustomRuleParamsWithHTTPClient(client *http.Client) *UpdateCustomRuleParams {
	var ()
	return &UpdateCustomRuleParams{
		HTTPClient: client,
	}
}

/*UpdateCustomRuleParams contains all the parameters to send to the API endpoint
for the update custom rule operation typically these are written to a http.Request
*/
type UpdateCustomRuleParams struct {

	/*Rule
	  New configuration options for the custom rule.

	*/
	Rule *models.UpdateCustomRuleInput
	/*RuleID
	  The id of the rule to update.

	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update custom rule params
func (o *UpdateCustomRuleParams) WithTimeout(timeout time.Duration) *UpdateCustomRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update custom rule params
func (o *UpdateCustomRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update custom rule params
func (o *UpdateCustomRuleParams) WithContext(ctx context.Context) *UpdateCustomRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update custom rule params
func (o *UpdateCustomRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update custom rule params
func (o *UpdateCustomRuleParams) WithHTTPClient(client *http.Client) *UpdateCustomRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update custom rule params
func (o *UpdateCustomRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRule adds the rule to the update custom rule params
func (o *UpdateCustomRuleParams) WithRule(rule *models.UpdateCustomRuleInput) *UpdateCustomRuleParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the update custom rule params
func (o *UpdateCustomRuleParams) SetRule(rule *models.UpdateCustomRuleInput) {
	o.Rule = rule
}

// WithRuleID adds the ruleID to the update custom rule params
func (o *UpdateCustomRuleParams) WithRuleID(ruleID string) *UpdateCustomRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the update custom rule params
func (o *UpdateCustomRuleParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCustomRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Rule != nil {
		if err := r.SetBodyParam(o.Rule); err != nil {
			return err
		}
	}

	// path param rule_id
	if err := r.SetPathParam("rule_id", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
