# Copyright 2020 Fugue, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This package was automatically generated from:
#
#     tests/rules/azure/inputs/storage_container_private_access_infra.tf
#
# using `generate_test_inputs.sh` and should not be modified
# directly.
#
# It provides three inputs for testing:
# - mock_input: The resource view input as passed to advanced rules
# - mock_resources: The resources present as a convenience for tests
# - mock_plan_input: The original plan input as generated by terraform
package tests.rules.azure.inputs.storage_container_private_access_infra
import data.fugue.resource_view.resource_view_input
mock_input = ret {
  ret = resource_view_input with input as mock_plan_input
}
mock_resources = mock_input.resources
mock_plan_input = {
  "format_version": "0.1",
  "terraform_version": "0.12.18",
  "planned_values": {
    "root_module": {
      "resources": [
        {
          "address": "azurerm_resource_group.example",
          "mode": "managed",
          "type": "azurerm_resource_group",
          "name": "example",
          "provider_name": "azurerm",
          "schema_version": 0,
          "values": {
            "location": "westeurope",
            "name": "example-resources",
            "tags": null,
            "timeouts": null
          }
        },
        {
          "address": "azurerm_storage_account.example",
          "mode": "managed",
          "type": "azurerm_storage_account",
          "name": "example",
          "provider_name": "azurerm",
          "schema_version": 2,
          "values": {
            "account_kind": "StorageV2",
            "account_replication_type": "LRS",
            "account_tier": "Standard",
            "allow_blob_public_access": false,
            "custom_domain": [],
            "enable_https_traffic_only": true,
            "is_hns_enabled": false,
            "location": "westeurope",
            "min_tls_version": "TLS1_0",
            "name": "examplestoraccount",
            "resource_group_name": "example-resources",
            "static_website": [],
            "tags": {
              "environment": "staging"
            },
            "timeouts": null
          }
        },
        {
          "address": "azurerm_storage_container.invalidcontainer1",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "invalidcontainer1",
          "provider_name": "azurerm",
          "schema_version": 1,
          "values": {
            "container_access_type": "container",
            "name": "invalidcontainer1",
            "storage_account_name": "examplestoraccount",
            "timeouts": null
          }
        },
        {
          "address": "azurerm_storage_container.validcontainer1",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "validcontainer1",
          "provider_name": "azurerm",
          "schema_version": 1,
          "values": {
            "container_access_type": "private",
            "name": "validcontainer1",
            "storage_account_name": "examplestoraccount",
            "timeouts": null
          }
        },
        {
          "address": "azurerm_storage_container.validcontainer2",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "validcontainer2",
          "provider_name": "azurerm",
          "schema_version": 1,
          "values": {
            "container_access_type": "private",
            "name": "validcontainer2",
            "storage_account_name": "examplestoraccount",
            "timeouts": null
          }
        }
      ]
    }
  },
  "resource_changes": [
    {
      "address": "azurerm_resource_group.example",
      "mode": "managed",
      "type": "azurerm_resource_group",
      "name": "example",
      "provider_name": "azurerm",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "location": "westeurope",
          "name": "example-resources",
          "tags": null,
          "timeouts": null
        },
        "after_unknown": {
          "id": true
        }
      }
    },
    {
      "address": "azurerm_storage_account.example",
      "mode": "managed",
      "type": "azurerm_storage_account",
      "name": "example",
      "provider_name": "azurerm",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "account_kind": "StorageV2",
          "account_replication_type": "LRS",
          "account_tier": "Standard",
          "allow_blob_public_access": false,
          "custom_domain": [],
          "enable_https_traffic_only": true,
          "is_hns_enabled": false,
          "location": "westeurope",
          "min_tls_version": "TLS1_0",
          "name": "examplestoraccount",
          "resource_group_name": "example-resources",
          "static_website": [],
          "tags": {
            "environment": "staging"
          },
          "timeouts": null
        },
        "after_unknown": {
          "access_tier": true,
          "blob_properties": true,
          "custom_domain": [],
          "id": true,
          "identity": true,
          "large_file_share_enabled": true,
          "network_rules": true,
          "primary_access_key": true,
          "primary_blob_connection_string": true,
          "primary_blob_endpoint": true,
          "primary_blob_host": true,
          "primary_connection_string": true,
          "primary_dfs_endpoint": true,
          "primary_dfs_host": true,
          "primary_file_endpoint": true,
          "primary_file_host": true,
          "primary_location": true,
          "primary_queue_endpoint": true,
          "primary_queue_host": true,
          "primary_table_endpoint": true,
          "primary_table_host": true,
          "primary_web_endpoint": true,
          "primary_web_host": true,
          "queue_properties": true,
          "secondary_access_key": true,
          "secondary_blob_connection_string": true,
          "secondary_blob_endpoint": true,
          "secondary_blob_host": true,
          "secondary_connection_string": true,
          "secondary_dfs_endpoint": true,
          "secondary_dfs_host": true,
          "secondary_file_endpoint": true,
          "secondary_file_host": true,
          "secondary_location": true,
          "secondary_queue_endpoint": true,
          "secondary_queue_host": true,
          "secondary_table_endpoint": true,
          "secondary_table_host": true,
          "secondary_web_endpoint": true,
          "secondary_web_host": true,
          "static_website": [],
          "tags": {}
        }
      }
    },
    {
      "address": "azurerm_storage_container.invalidcontainer1",
      "mode": "managed",
      "type": "azurerm_storage_container",
      "name": "invalidcontainer1",
      "provider_name": "azurerm",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "container_access_type": "container",
          "name": "invalidcontainer1",
          "storage_account_name": "examplestoraccount",
          "timeouts": null
        },
        "after_unknown": {
          "has_immutability_policy": true,
          "has_legal_hold": true,
          "id": true,
          "metadata": true,
          "resource_manager_id": true
        }
      }
    },
    {
      "address": "azurerm_storage_container.validcontainer1",
      "mode": "managed",
      "type": "azurerm_storage_container",
      "name": "validcontainer1",
      "provider_name": "azurerm",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "container_access_type": "private",
          "name": "validcontainer1",
          "storage_account_name": "examplestoraccount",
          "timeouts": null
        },
        "after_unknown": {
          "has_immutability_policy": true,
          "has_legal_hold": true,
          "id": true,
          "metadata": true,
          "resource_manager_id": true
        }
      }
    },
    {
      "address": "azurerm_storage_container.validcontainer2",
      "mode": "managed",
      "type": "azurerm_storage_container",
      "name": "validcontainer2",
      "provider_name": "azurerm",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "container_access_type": "private",
          "name": "validcontainer2",
          "storage_account_name": "examplestoraccount",
          "timeouts": null
        },
        "after_unknown": {
          "has_immutability_policy": true,
          "has_legal_hold": true,
          "id": true,
          "metadata": true,
          "resource_manager_id": true
        }
      }
    }
  ],
  "configuration": {
    "provider_config": {
      "azurerm": {
        "name": "azurerm",
        "expressions": {
          "features": [
            {}
          ]
        }
      }
    },
    "root_module": {
      "resources": [
        {
          "address": "azurerm_resource_group.example",
          "mode": "managed",
          "type": "azurerm_resource_group",
          "name": "example",
          "provider_config_key": "azurerm",
          "expressions": {
            "location": {
              "constant_value": "West Europe"
            },
            "name": {
              "constant_value": "example-resources"
            }
          },
          "schema_version": 0
        },
        {
          "address": "azurerm_storage_account.example",
          "mode": "managed",
          "type": "azurerm_storage_account",
          "name": "example",
          "provider_config_key": "azurerm",
          "expressions": {
            "account_replication_type": {
              "constant_value": "LRS"
            },
            "account_tier": {
              "constant_value": "Standard"
            },
            "location": {
              "references": [
                "azurerm_resource_group.example"
              ]
            },
            "name": {
              "constant_value": "examplestoraccount"
            },
            "resource_group_name": {
              "references": [
                "azurerm_resource_group.example"
              ]
            },
            "tags": {
              "constant_value": {
                "environment": "staging"
              }
            }
          },
          "schema_version": 2
        },
        {
          "address": "azurerm_storage_container.invalidcontainer1",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "invalidcontainer1",
          "provider_config_key": "azurerm",
          "expressions": {
            "container_access_type": {
              "constant_value": "container"
            },
            "name": {
              "constant_value": "invalidcontainer1"
            },
            "storage_account_name": {
              "references": [
                "azurerm_storage_account.example"
              ]
            }
          },
          "schema_version": 1
        },
        {
          "address": "azurerm_storage_container.validcontainer1",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "validcontainer1",
          "provider_config_key": "azurerm",
          "expressions": {
            "container_access_type": {
              "constant_value": "private"
            },
            "name": {
              "constant_value": "validcontainer1"
            },
            "storage_account_name": {
              "references": [
                "azurerm_storage_account.example"
              ]
            }
          },
          "schema_version": 1
        },
        {
          "address": "azurerm_storage_container.validcontainer2",
          "mode": "managed",
          "type": "azurerm_storage_container",
          "name": "validcontainer2",
          "provider_config_key": "azurerm",
          "expressions": {
            "name": {
              "constant_value": "validcontainer2"
            },
            "storage_account_name": {
              "references": [
                "azurerm_storage_account.example"
              ]
            }
          },
          "schema_version": 1
        }
      ]
    }
  }
}
