// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fugue/regula/v2/pkg/swagger/models"
)

// EditUsersGroupAssignmentsReader is a Reader for the EditUsersGroupAssignments structure.
type EditUsersGroupAssignmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditUsersGroupAssignmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEditUsersGroupAssignmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEditUsersGroupAssignmentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewEditUsersGroupAssignmentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEditUsersGroupAssignmentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEditUsersGroupAssignmentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEditUsersGroupAssignmentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEditUsersGroupAssignmentsOK creates a EditUsersGroupAssignmentsOK with default headers values
func NewEditUsersGroupAssignmentsOK() *EditUsersGroupAssignmentsOK {
	return &EditUsersGroupAssignmentsOK{}
}

/*EditUsersGroupAssignmentsOK handles this case with default header values.

User Group assignment updated.
*/
type EditUsersGroupAssignmentsOK struct {
}

func (o *EditUsersGroupAssignmentsOK) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsOK ", 200)
}

func (o *EditUsersGroupAssignmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditUsersGroupAssignmentsBadRequest creates a EditUsersGroupAssignmentsBadRequest with default headers values
func NewEditUsersGroupAssignmentsBadRequest() *EditUsersGroupAssignmentsBadRequest {
	return &EditUsersGroupAssignmentsBadRequest{}
}

/*EditUsersGroupAssignmentsBadRequest handles this case with default header values.

BadRequestError
*/
type EditUsersGroupAssignmentsBadRequest struct {
	Payload *models.BadRequestError
}

func (o *EditUsersGroupAssignmentsBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsBadRequest  %+v", 400, o.Payload)
}

func (o *EditUsersGroupAssignmentsBadRequest) GetPayload() *models.BadRequestError {
	return o.Payload
}

func (o *EditUsersGroupAssignmentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditUsersGroupAssignmentsUnauthorized creates a EditUsersGroupAssignmentsUnauthorized with default headers values
func NewEditUsersGroupAssignmentsUnauthorized() *EditUsersGroupAssignmentsUnauthorized {
	return &EditUsersGroupAssignmentsUnauthorized{}
}

/*EditUsersGroupAssignmentsUnauthorized handles this case with default header values.

AuthenticationError
*/
type EditUsersGroupAssignmentsUnauthorized struct {
	Payload *models.AuthenticationError
}

func (o *EditUsersGroupAssignmentsUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsUnauthorized  %+v", 401, o.Payload)
}

func (o *EditUsersGroupAssignmentsUnauthorized) GetPayload() *models.AuthenticationError {
	return o.Payload
}

func (o *EditUsersGroupAssignmentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditUsersGroupAssignmentsForbidden creates a EditUsersGroupAssignmentsForbidden with default headers values
func NewEditUsersGroupAssignmentsForbidden() *EditUsersGroupAssignmentsForbidden {
	return &EditUsersGroupAssignmentsForbidden{}
}

/*EditUsersGroupAssignmentsForbidden handles this case with default header values.

AuthorizationError
*/
type EditUsersGroupAssignmentsForbidden struct {
	Payload *models.AuthorizationError
}

func (o *EditUsersGroupAssignmentsForbidden) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsForbidden  %+v", 403, o.Payload)
}

func (o *EditUsersGroupAssignmentsForbidden) GetPayload() *models.AuthorizationError {
	return o.Payload
}

func (o *EditUsersGroupAssignmentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthorizationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditUsersGroupAssignmentsNotFound creates a EditUsersGroupAssignmentsNotFound with default headers values
func NewEditUsersGroupAssignmentsNotFound() *EditUsersGroupAssignmentsNotFound {
	return &EditUsersGroupAssignmentsNotFound{}
}

/*EditUsersGroupAssignmentsNotFound handles this case with default header values.

NotFoundError
*/
type EditUsersGroupAssignmentsNotFound struct {
	Payload *models.NotFoundError
}

func (o *EditUsersGroupAssignmentsNotFound) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsNotFound  %+v", 404, o.Payload)
}

func (o *EditUsersGroupAssignmentsNotFound) GetPayload() *models.NotFoundError {
	return o.Payload
}

func (o *EditUsersGroupAssignmentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditUsersGroupAssignmentsInternalServerError creates a EditUsersGroupAssignmentsInternalServerError with default headers values
func NewEditUsersGroupAssignmentsInternalServerError() *EditUsersGroupAssignmentsInternalServerError {
	return &EditUsersGroupAssignmentsInternalServerError{}
}

/*EditUsersGroupAssignmentsInternalServerError handles this case with default header values.

InternalServerError
*/
type EditUsersGroupAssignmentsInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *EditUsersGroupAssignmentsInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /users][%d] editUsersGroupAssignmentsInternalServerError  %+v", 500, o.Payload)
}

func (o *EditUsersGroupAssignmentsInternalServerError) GetPayload() *models.InternalServerError {
	return o.Payload
}

func (o *EditUsersGroupAssignmentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
