// Code generated by go-swagger; DO NOT EDIT.

package scans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetComplianceByRulesParams creates a new GetComplianceByRulesParams object
// with the default values initialized.
func NewGetComplianceByRulesParams() *GetComplianceByRulesParams {
	var (
		maxItemsDefault = int64(100)
		offsetDefault   = int64(0)
	)
	return &GetComplianceByRulesParams{
		MaxItems: &maxItemsDefault,
		Offset:   &offsetDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetComplianceByRulesParamsWithTimeout creates a new GetComplianceByRulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetComplianceByRulesParamsWithTimeout(timeout time.Duration) *GetComplianceByRulesParams {
	var (
		maxItemsDefault = int64(100)
		offsetDefault   = int64(0)
	)
	return &GetComplianceByRulesParams{
		MaxItems: &maxItemsDefault,
		Offset:   &offsetDefault,

		timeout: timeout,
	}
}

// NewGetComplianceByRulesParamsWithContext creates a new GetComplianceByRulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetComplianceByRulesParamsWithContext(ctx context.Context) *GetComplianceByRulesParams {
	var (
		maxItemsDefault = int64(100)
		offsetDefault   = int64(0)
	)
	return &GetComplianceByRulesParams{
		MaxItems: &maxItemsDefault,
		Offset:   &offsetDefault,

		Context: ctx,
	}
}

// NewGetComplianceByRulesParamsWithHTTPClient creates a new GetComplianceByRulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetComplianceByRulesParamsWithHTTPClient(client *http.Client) *GetComplianceByRulesParams {
	var (
		maxItemsDefault = int64(100)
		offsetDefault   = int64(0)
	)
	return &GetComplianceByRulesParams{
		MaxItems:   &maxItemsDefault,
		Offset:     &offsetDefault,
		HTTPClient: client,
	}
}

/*GetComplianceByRulesParams contains all the parameters to send to the API endpoint
for the get compliance by rules operation typically these are written to a http.Request
*/
type GetComplianceByRulesParams struct {

	/*Family
	  Compliance family to filter by. When not specified, all compliance families will be returned.

	*/
	Family []string
	/*MaxItems
	  Maximum number of items to return.

	*/
	MaxItems *int64
	/*Offset
	  Number of items to skip before returning. This parameter is used when the number of items spans multiple pages.

	*/
	Offset *int64
	/*Result
	  Rule result to filter by. When not specified, all results will be returned.

	*/
	Result []string
	/*ScanID
	  Scan ID.

	*/
	ScanID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithTimeout(timeout time.Duration) *GetComplianceByRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithContext(ctx context.Context) *GetComplianceByRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithHTTPClient(client *http.Client) *GetComplianceByRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFamily adds the family to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithFamily(family []string) *GetComplianceByRulesParams {
	o.SetFamily(family)
	return o
}

// SetFamily adds the family to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetFamily(family []string) {
	o.Family = family
}

// WithMaxItems adds the maxItems to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithMaxItems(maxItems *int64) *GetComplianceByRulesParams {
	o.SetMaxItems(maxItems)
	return o
}

// SetMaxItems adds the maxItems to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetMaxItems(maxItems *int64) {
	o.MaxItems = maxItems
}

// WithOffset adds the offset to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithOffset(offset *int64) *GetComplianceByRulesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithResult adds the result to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithResult(result []string) *GetComplianceByRulesParams {
	o.SetResult(result)
	return o
}

// SetResult adds the result to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetResult(result []string) {
	o.Result = result
}

// WithScanID adds the scanID to the get compliance by rules params
func (o *GetComplianceByRulesParams) WithScanID(scanID string) *GetComplianceByRulesParams {
	o.SetScanID(scanID)
	return o
}

// SetScanID adds the scanId to the get compliance by rules params
func (o *GetComplianceByRulesParams) SetScanID(scanID string) {
	o.ScanID = scanID
}

// WriteToRequest writes these params to a swagger request
func (o *GetComplianceByRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesFamily := o.Family

	joinedFamily := swag.JoinByFormat(valuesFamily, "multi")
	// query array param family
	if err := r.SetQueryParam("family", joinedFamily...); err != nil {
		return err
	}

	if o.MaxItems != nil {

		// query param max_items
		var qrMaxItems int64
		if o.MaxItems != nil {
			qrMaxItems = *o.MaxItems
		}
		qMaxItems := swag.FormatInt64(qrMaxItems)
		if qMaxItems != "" {
			if err := r.SetQueryParam("max_items", qMaxItems); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesResult := o.Result

	joinedResult := swag.JoinByFormat(valuesResult, "multi")
	// query array param result
	if err := r.SetQueryParam("result", joinedResult...); err != nil {
		return err
	}

	// path param scan_id
	if err := r.SetPathParam("scan_id", o.ScanID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
