// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateFamilyInput Input request for creating a family.
//
// swagger:model CreateFamilyInput
type CreateFamilyInput struct {

	// If the family will automatically be enabled on all environments within the tenant
	AlwaysEnabled bool `json:"always_enabled,omitempty"`

	// Description of the family
	Description string `json:"description,omitempty"`

	// Human readable name of the family
	Name string `json:"name,omitempty"`

	// If the family is recommended for all new environments
	Recommended bool `json:"recommended,omitempty"`

	// List of rule ids to associate with family
	RuleIds []string `json:"rule_ids"`
}

// Validate validates this create family input
func (m *CreateFamilyInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateFamilyInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFamilyInput) UnmarshalBinary(b []byte) error {
	var res CreateFamilyInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
