// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PermissionsAws IAM policy required for surveying and remediating the desired resource types.
//
// swagger:model PermissionsAws
type PermissionsAws struct {

	// JSON policy for surveying and remediating the desired resource types.
	Policy interface{} `json:"policy,omitempty"`

	// JSON trust relationship for IAM role
	TrustRelationship interface{} `json:"trust_relationship,omitempty"`
}

// Validate validates this permissions aws
func (m *PermissionsAws) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PermissionsAws) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PermissionsAws) UnmarshalBinary(b []byte) error {
	var res PermissionsAws
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
