// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourceTypeMetadata List of resource types supported by Fugue.
//
// swagger:model ResourceTypeMetadata
type ResourceTypeMetadata struct {

	// List of Fugue recommended resource types.
	RecommendedTypes []string `json:"recommended_types"`

	// List of resource types supported by Fugue.
	ResourceTypes []string `json:"resource_types"`
}

// Validate validates this resource type metadata
func (m *ResourceTypeMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceTypeMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceTypeMetadata) UnmarshalBinary(b []byte) error {
	var res ResourceTypeMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
