// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScanWithSummary A scan belonging to an environment.
//
// swagger:model ScanWithSummary
type ScanWithSummary struct {
	Scan

	// resource summary
	ResourceSummary *ResourceSummary `json:"resource_summary,omitempty"`

	// resource type errors
	ResourceTypeErrors []*ScanWithSummaryResourceTypeErrorsItems0 `json:"resource_type_errors"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ScanWithSummary) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Scan
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Scan = aO0

	// AO1
	var dataAO1 struct {
		ResourceSummary *ResourceSummary `json:"resource_summary,omitempty"`

		ResourceTypeErrors []*ScanWithSummaryResourceTypeErrorsItems0 `json:"resource_type_errors"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.ResourceSummary = dataAO1.ResourceSummary

	m.ResourceTypeErrors = dataAO1.ResourceTypeErrors

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ScanWithSummary) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Scan)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		ResourceSummary *ResourceSummary `json:"resource_summary,omitempty"`

		ResourceTypeErrors []*ScanWithSummaryResourceTypeErrorsItems0 `json:"resource_type_errors"`
	}

	dataAO1.ResourceSummary = m.ResourceSummary

	dataAO1.ResourceTypeErrors = m.ResourceTypeErrors

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this scan with summary
func (m *ScanWithSummary) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Scan
	if err := m.Scan.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceSummary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceTypeErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScanWithSummary) validateResourceSummary(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceSummary) { // not required
		return nil
	}

	if m.ResourceSummary != nil {
		if err := m.ResourceSummary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_summary")
			}
			return err
		}
	}

	return nil
}

func (m *ScanWithSummary) validateResourceTypeErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceTypeErrors) { // not required
		return nil
	}

	for i := 0; i < len(m.ResourceTypeErrors); i++ {
		if swag.IsZero(m.ResourceTypeErrors[i]) { // not required
			continue
		}

		if m.ResourceTypeErrors[i] != nil {
			if err := m.ResourceTypeErrors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resource_type_errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScanWithSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScanWithSummary) UnmarshalBinary(b []byte) error {
	var res ScanWithSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ScanWithSummaryResourceTypeErrorsItems0 scan with summary resource type errors items0
//
// swagger:model ScanWithSummaryResourceTypeErrorsItems0
type ScanWithSummaryResourceTypeErrorsItems0 struct {

	// error message
	// Required: true
	ErrorMessage *string `json:"error_message"`

	// resource type
	// Required: true
	ResourceType *string `json:"resource_type"`
}

// Validate validates this scan with summary resource type errors items0
func (m *ScanWithSummaryResourceTypeErrorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrorMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScanWithSummaryResourceTypeErrorsItems0) validateErrorMessage(formats strfmt.Registry) error {

	if err := validate.Required("error_message", "body", m.ErrorMessage); err != nil {
		return err
	}

	return nil
}

func (m *ScanWithSummaryResourceTypeErrorsItems0) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("resource_type", "body", m.ResourceType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ScanWithSummaryResourceTypeErrorsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScanWithSummaryResourceTypeErrorsItems0) UnmarshalBinary(b []byte) error {
	var res ScanWithSummaryResourceTypeErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
