// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRuleWaiverInput Used to update properties of a rule waiver
//
// swagger:model UpdateRuleWaiverInput
type UpdateRuleWaiverInput struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update rule waiver input
func (m *UpdateRuleWaiverInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRuleWaiverInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRuleWaiverInput) UnmarshalBinary(b []byte) error {
	var res UpdateRuleWaiverInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
