// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadRegulaScanViewOutput Options for uploading regula scan view
//
// swagger:model UploadRegulaScanViewOutput
type UploadRegulaScanViewOutput struct {

	// Presigned S3 URL to upload a scan view
	URL string `json:"url,omitempty"`
}

// Validate validates this upload regula scan view output
func (m *UploadRegulaScanViewOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadRegulaScanViewOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadRegulaScanViewOutput) UnmarshalBinary(b []byte) error {
	var res UploadRegulaScanViewOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
