// Code generated by go-swagger; DO NOT EDIT.

package rule_waivers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fugue/regula/v2/pkg/swagger/models"
)

// NewUpdateRuleWaiverParams creates a new UpdateRuleWaiverParams object
// with the default values initialized.
func NewUpdateRuleWaiverParams() *UpdateRuleWaiverParams {
	var ()
	return &UpdateRuleWaiverParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRuleWaiverParamsWithTimeout creates a new UpdateRuleWaiverParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRuleWaiverParamsWithTimeout(timeout time.Duration) *UpdateRuleWaiverParams {
	var ()
	return &UpdateRuleWaiverParams{

		timeout: timeout,
	}
}

// NewUpdateRuleWaiverParamsWithContext creates a new UpdateRuleWaiverParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRuleWaiverParamsWithContext(ctx context.Context) *UpdateRuleWaiverParams {
	var ()
	return &UpdateRuleWaiverParams{

		Context: ctx,
	}
}

// NewUpdateRuleWaiverParamsWithHTTPClient creates a new UpdateRuleWaiverParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRuleWaiverParamsWithHTTPClient(client *http.Client) *UpdateRuleWaiverParams {
	var ()
	return &UpdateRuleWaiverParams{
		HTTPClient: client,
	}
}

/*UpdateRuleWaiverParams contains all the parameters to send to the API endpoint
for the update rule waiver operation typically these are written to a http.Request
*/
type UpdateRuleWaiverParams struct {

	/*Input
	  Rule waiver update parameters

	*/
	Input *models.UpdateRuleWaiverInput
	/*RuleWaiverID
	  The ID of rule waiver to update

	*/
	RuleWaiverID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update rule waiver params
func (o *UpdateRuleWaiverParams) WithTimeout(timeout time.Duration) *UpdateRuleWaiverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update rule waiver params
func (o *UpdateRuleWaiverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update rule waiver params
func (o *UpdateRuleWaiverParams) WithContext(ctx context.Context) *UpdateRuleWaiverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update rule waiver params
func (o *UpdateRuleWaiverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update rule waiver params
func (o *UpdateRuleWaiverParams) WithHTTPClient(client *http.Client) *UpdateRuleWaiverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update rule waiver params
func (o *UpdateRuleWaiverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the update rule waiver params
func (o *UpdateRuleWaiverParams) WithInput(input *models.UpdateRuleWaiverInput) *UpdateRuleWaiverParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the update rule waiver params
func (o *UpdateRuleWaiverParams) SetInput(input *models.UpdateRuleWaiverInput) {
	o.Input = input
}

// WithRuleWaiverID adds the ruleWaiverID to the update rule waiver params
func (o *UpdateRuleWaiverParams) WithRuleWaiverID(ruleWaiverID string) *UpdateRuleWaiverParams {
	o.SetRuleWaiverID(ruleWaiverID)
	return o
}

// SetRuleWaiverID adds the ruleWaiverId to the update rule waiver params
func (o *UpdateRuleWaiverParams) SetRuleWaiverID(ruleWaiverID string) {
	o.RuleWaiverID = ruleWaiverID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRuleWaiverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	// path param rule_waiver_id
	if err := r.SetPathParam("rule_waiver_id", o.RuleWaiverID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
